DROP DATABASE IF EXISTS eaglelogger;

CREATE DATABASE eaglelogger;

GRANT ALL on eaglelogger.* TO elncs@localhost IDENTIFIED BY 'I am KM4FPA';

USE eaglelogger;

CREATE TABLE nets(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	dt TIMESTAMP,
	ndate DATE,
	start DATETIME,
	end DATETIME,
	ncs_id INT UNSIGNED,
	traffic TINYINT UNSIGNED,
	active BOOLEAN DEFAULT 1,
	valid BOOLEAN DEFAULT 1,
	PRIMARY KEY(id)
) ENGINE InnoDB; 

CREATE TABLE checkins(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	dt TIMESTAMP,
	line TINYINT UNSIGNED,
	cid INT UNSIGNED,
	nid INT UNSIGNED,
	traffic BOOLEAN DEFAULT 0,
	PRIMARY KEY(id),
	UNIQUE KEY(cid, nid)
) ENGINE InnoDB; 

CREATE TABLE announcements(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	dt TIMESTAMP,
	nid INT UNSIGNED,
	announcement VARCHAR(512),
	PRIMARY KEY(id)
) ENGINE InnoDB; 

CREATE TABLE callsigns(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	dt TIMESTAMP,
	callsign VARCHAR(6),
	name VARCHAR(16),
	city VARCHAR(32),
	county VARCHAR(32),
	address VARCHAR(64),
	phone VARCHAR(16),
	qrz VARCHAR(32),
	website VARCHAR(64),
	email VARCHAR(64),
	jobs VARCHAR(256),
	ncs BOOLEAN DEFAULT 0,
	valid BOOLEAN DEFAULT 1,
	PRIMARY KEY(id)
) ENGINE InnoDB; 

CREATE TABLE users(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	cid INT UNSIGNED,
	password VARCHAR(64),
	PRIMARY KEY(id)
) ENGINE InnoDB; 

CREATE TABLE rights(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	uid INT UNSIGNED,
	rite VARCHAR(12),
	PRIMARY KEY(id)
) ENGINE InnoDB; 

CREATE TABLE tokens(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	uid INT UNSIGNED,
	token VARCHAR(64),
	PRIMARY KEY(id)
) ENGINE InnoDB; 


CREATE TABLE chat (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	column
	PRIMARY KEY(id)
) ENGINE InnoDB;